### ISSUE TITLE
Improvement in UI

### ISSUE THREAD

**Issue by amanjagdev** [navya252001/to-do-list#1]
I feel that we can do some minor improvements that can be done in the UI to make it better and more responsive.
For example, that edit button beside every item doesn't work so we can rather remove it.

This was just one example I feel that I can do more improvements.
Please tell me if this seems a valid issue to you and I can start working on it.
![image](https://user-images.githubusercontent.com/34389172/94775561-affa3c00-03dd-11eb-9c96-b8a68b120228.png)

**Comment by dahiya-code** [comment]
Yes you may

**Comment by dahiya-code** [comment]
May the edit button working

**Comment by amanjagdev** [comment]
> May the edit button working

Okay I will also see to it

**Comment by dahiya-code** [comment]
*make

**Comment by amanjagdev** [comment]
Can I change your JS code?
Because I feel there is no maintenance of the items of todo list in the memory i.e in js.
So I can add that :)

**Comment by dahiya-code** [comment]
yes

**Comment by amanjagdev** [comment]
@navya252001  Please take a look at the PR #2 It resolves this issue :)
